# generated by scaffold-guard; edit scaffold-guard.toml or rerun scaffold-guard compile-rules

# Warning-only Codex workflow evidence hook. It records lightweight local
# evidence and must not block the agent loop.

set -u

event="${1:-unknown}"
root="${2:-}"
subject="${3:-}"

warn() {
  printf '%s\n' "scaffold-guard generated: workflow evidence warning: $*" >&2
}

json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

if [ -z "$root" ]; then
  start="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
  root="$start"
  while [ "$root" != "/" ] && [ ! -f "$root/scaffold-guard.toml" ]; do
    root="$(dirname "$root")"
  done
  if [ ! -f "$root/scaffold-guard.toml" ]; then
    root="$start"
  fi
fi

if [ ! -d "$root" ]; then
  warn "project root is not a directory: $root"
  exit 0
fi

if [ -n "${CODEX_WORKFLOW_EVIDENCE_LOG:-}" ]; then
  log_path="$CODEX_WORKFLOW_EVIDENCE_LOG"
else
  git_dir="$(git -C "$root" rev-parse --git-dir 2>/dev/null || true)"
  if [ -n "$git_dir" ]; then
    case "$git_dir" in
      /*) evidence_dir="$git_dir/scaffold-guard" ;;
      *) evidence_dir="$root/$git_dir/scaffold-guard" ;;
    esac
    log_path="$evidence_dir/codex-workflow-evidence.jsonl"
  else
    checksum="$(printf '%s' "$root" | cksum | awk '{print $1}' 2>/dev/null || printf 'unknown')"
    log_path="${TMPDIR:-/tmp}/scaffold-guard-codex-evidence/${checksum}.jsonl"
  fi
fi

state_path="${log_path}.state"
log_dir="$(dirname "$log_path")"
umask 077
if ! mkdir -p "$log_dir" 2>/dev/null; then
  warn "could not create evidence directory: $log_dir"
  exit 0
fi

mark_state() {
  key="$1"
  tmp_path="${state_path}.$$"
  if [ -f "$state_path" ]; then
    grep -v "^${key}=" "$state_path" > "$tmp_path" 2>/dev/null || true
  else
    : > "$tmp_path"
  fi
  printf '%s=1\n' "$key" >> "$tmp_path"
  mv "$tmp_path" "$state_path" 2>/dev/null || true
}

state_has() {
  key="$1"
  [ -f "$state_path" ] && grep -q "^${key}=1$" "$state_path" 2>/dev/null
}

timestamp="$(date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || date)"
branch="$(git -C "$root" branch --show-current 2>/dev/null || true)"
changed_files="$(git -C "$root" status --short 2>/dev/null | wc -l | tr -d ' ')"
case "$changed_files" in
  ''|*[!0-9]*) changed_files=0 ;;
esac

record="$(printf '{"source":"codex-hook","event":"%s","subject":"%s","root":"%s","branch":"%s","changed_files":%s,"timestamp":"%s"}\n' \
  "$(json_escape "$event")" \
  "$(json_escape "$subject")" \
  "$(json_escape "$root")" \
  "$(json_escape "$branch")" \
  "$changed_files" \
  "$(json_escape "$timestamp")")"

if ! printf '%s\n' "$record" >> "$log_path" 2>/dev/null; then
  warn "could not append evidence to: $log_path"
fi

case "$event:$subject" in
  post-tool-use:edit)
    mark_state "EDIT_OCCURRED"
    ;;
  subagent-start:*)
    mark_state "SUBAGENT_STARTED"
    ;;
  subagent-stop:*)
    mark_state "SUBAGENT_STOPPED"
    ;;
  stop:*)
    if state_has "EDIT_OCCURRED" && ! state_has "SUBAGENT_STARTED"; then
      warn "file edits were observed, but no SubagentStart evidence was recorded. For non-trivial implementation work, spawn a worker subagent before substantial local edits."
    fi
    rm -f "$state_path" 2>/dev/null || true
    ;;
esac

exit 0
