import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";

import type { CloudRunLogsVerifyReport } from "./cloudRunLogsVerifyCore.js";
import { evidenceTextSafetyProblem } from "./v1EvidenceSafety.js";
import { formatV1RecordCommand, shellArg } from "./v1RecordCommandFormat.js";

const DEFAULT_GATE_16_ARTIFACT = ".data/v1/gate-16-cloud-run-logs.md";

export interface WriteCloudRunLogsEvidenceOptions {
  readonly cwd: string;
  readonly artifact: string;
  readonly report: CloudRunLogsVerifyReport;
  readonly verifiedAt?: string | undefined;
}

export interface WriteCloudRunLogsEvidenceResult {
  readonly artifact: string;
  readonly path: string;
}

export function writeCloudRunLogsEvidenceArtifact(
  options: WriteCloudRunLogsEvidenceOptions,
): WriteCloudRunLogsEvidenceResult {
  const { artifact, path } = resolveProjectArtifact(
    options.cwd,
    options.artifact,
  );
  const markdown = renderCloudRunLogsEvidenceArtifact(
    options.report,
    options.verifiedAt ?? new Date().toISOString(),
    artifact,
  );
  const safetyProblem = evidenceTextSafetyProblem(
    `artifact ${artifact}`,
    markdown,
  );
  if (safetyProblem) {
    throw new Error(safetyProblem);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, markdown);

  return {
    artifact,
    path,
  };
}

export function renderCloudRunLogsEvidenceArtifact(
  report: CloudRunLogsVerifyReport,
  verifiedAt: string,
  artifact = DEFAULT_GATE_16_ARTIFACT,
): string {
  return `${[
    "# V1 Cloud Run Log Safety Evidence",
    "",
    "This artifact is generated by the Cloud Run log verifier. It records summary metadata only; do not add raw log entries, request or response bodies, cookies, bearer tokens, Substack session values, confirmation tokens, or draft contents.",
    "",
    "## Exported Log Verification",
    "",
    `- Verified at: ${verifiedAt}`,
    `- Complete: ${report.ok ? "yes" : "no"}`,
    `- Exported entries parsed: ${report.entry_count}`,
    `- Audit events found: ${report.audit_event_count}`,
    "",
    "## Checks",
    "",
    ...report.checks.map(
      (check) =>
        `- [${check.ok ? "x" : " "}] ${safeCheckLabel(check.id)}: ${
          check.evidence
        }`,
    ),
    "",
    "## Finding Summary",
    "",
    ...findingSummary(report),
    "",
    "## Required Evidence Checklist",
    "",
    "- [ ] Logs were exported after live Cloud Run acceptance traffic.",
    "- [ ] `cloud-run:logs:verify` completed with required audit events.",
    "- [ ] Exported logs contained no cookie, bearer-token, secret-environment, or private MCP path leaks.",
    "- [ ] Exported logs contained no draft content or request/response body fields.",
    "- [ ] Audit events were metadata-only and used the allowed field set.",
    "- [ ] Evidence was reviewed to confirm no raw log entries or secret values are included.",
    "",
    "## Manual Log Review Details",
    "",
    "Complete these fields after exporting logs from the live Cloud Run service. Leave out raw log entries, request or response bodies, cookies, bearer tokens, path secrets, Substack session values, confirmation tokens, and draft contents.",
    "",
    "- Log export window: <replace with live Cloud Run log export start/end time or query window>",
    "- Cloud Run service/revision: <replace with Cloud Run service name and revision or service URL reference>",
    "- Live traffic exercised: <replace with acceptance traffic summary>",
    "- Log export command: <replace with gcloud logging read command including Cloud Run resource filter>",
    "- Verifier command: <replace with cloud-run:logs:verify command including --logs-json and --require-audit-events>",
    "- Audit event review: <replace with audit count and metadata-only confirmation>",
    "- Finding review: <replace with no findings or sanitized finding-category/count summary>",
    "- Raw log handling: <replace with retained/deleted path and access decision>",
    "- Follow-up action: <replace with rotation/redeploy/no action and reason>",
    "",
    "## Suggested Record Command",
    "",
    "```bash",
    formatV1RecordCommand({
      gateId: 16,
      evidence:
        "Cloud Run log export passed secret and draft-content safety verification after live acceptance traffic",
      command: `npm run cloud-run:logs:verify -- --logs-json .data/cloud-run-logs.json --require-audit-events --evidence-artifact ${shellArg(artifact)}`,
      artifact,
    }),
    "```",
    "",
  ].join("\n")}\n`;
}

function findingSummary(report: CloudRunLogsVerifyReport): readonly string[] {
  if (report.findings.length === 0) {
    return ["No findings."];
  }

  const counts = new Map<string, number>();
  for (const finding of report.findings) {
    counts.set(finding.id, (counts.get(finding.id) ?? 0) + 1);
  }

  return [...counts.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([id, count]) => `- ${safeFindingLabel(id)}: ${count} finding(s)`);
}

function safeCheckLabel(id: string): string {
  switch (id) {
    case "log_entries_present":
      return "log entries present";
    case "no_secret_patterns_or_fields":
      return "no secret patterns or fields";
    case "no_draft_body_fields":
      return "no draft content fields";
    case "audit_events_metadata_only":
      return "audit events metadata only";
    default:
      return id.replace(/_/g, " ");
  }
}

function safeFindingLabel(id: string): string {
  switch (id) {
    case "secret_pattern":
      return "secret pattern";
    case "sensitive_field":
      return "sensitive field";
    case "draft_body_field":
      return "draft content field";
    case "unexpected_audit_field":
      return "unexpected audit field";
    default:
      return id.replace(/_/g, " ");
  }
}

function resolveProjectArtifact(
  cwd: string,
  value: string,
): { readonly artifact: string; readonly path: string } {
  const root = resolve(cwd);
  const path = resolve(root, value);
  const artifact = relative(root, path);
  if (artifact === "" || artifact.startsWith("..") || isAbsolute(artifact)) {
    throw new Error(
      "V1 Cloud Run logs evidence artifact must stay inside the project directory.",
    );
  }

  return { artifact, path };
}
