import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";

import type { CloudRunVerifyReport } from "./cloudRunVerifyCore.js";
import { evidenceTextSafetyProblem } from "./v1EvidenceSafety.js";
import { formatV1RecordCommand, shellArg } from "./v1RecordCommandFormat.js";

const DEFAULT_GATE_12_ARTIFACT = ".data/v1/gate-12-cloud-run-deployment.md";

export interface WriteCloudRunVerifyEvidenceOptions {
  readonly cwd: string;
  readonly artifact: string;
  readonly report: CloudRunVerifyReport;
  readonly verifiedAt?: string | undefined;
}

export interface WriteCloudRunVerifyEvidenceResult {
  readonly artifact: string;
  readonly path: string;
}

export function writeCloudRunVerifyEvidenceArtifact(
  options: WriteCloudRunVerifyEvidenceOptions,
): WriteCloudRunVerifyEvidenceResult {
  const { artifact, path } = resolveProjectArtifact(
    options.cwd,
    options.artifact,
  );
  const markdown = renderCloudRunVerifyEvidenceArtifact(
    options.report,
    options.verifiedAt ?? new Date().toISOString(),
    artifact,
  );
  const safetyProblem = evidenceTextSafetyProblem(
    `artifact ${artifact}`,
    markdown,
  );
  if (safetyProblem) {
    throw new Error(safetyProblem);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, markdown);

  return {
    artifact,
    path,
  };
}

export function renderCloudRunVerifyEvidenceArtifact(
  report: CloudRunVerifyReport,
  verifiedAt: string,
  artifact = DEFAULT_GATE_12_ARTIFACT,
): string {
  return `${[
    "# V1 Cloud Run Deployment Evidence",
    "",
    "This artifact is generated by the Cloud Run service verifier. It records safe deployed-service metadata only; do not add Secret Manager values, bearer tokens, Substack cookies, raw service JSON, raw logs, raw API responses, or full draft contents.",
    "",
    "## Exported Service Verification",
    "",
    `- Verified at: ${verifiedAt}`,
    `- Complete: ${report.ok ? "yes" : "no"}`,
    `- Auth mode: ${report.auth_mode}`,
    `- Service URL: ${report.service_url ?? "missing"}`,
    "",
    "## Checks",
    "",
    ...report.checks.flatMap((entry) => [
      `- [${entry.ok ? "x" : " "}] ${entry.id}`,
      `  - Evidence: ${entry.evidence}`,
      ...(entry.expected
        ? [`  - Expected: ${safeEvidenceDetail(entry.expected)}`]
        : []),
      ...(entry.actual
        ? [`  - Actual: ${safeEvidenceDetail(entry.actual)}`]
        : []),
    ]),
    "",
    "## Required Evidence Checklist",
    "",
    "- [ ] Exported service JSON came from the intended GCP project, region, and Cloud Run service.",
    "- [ ] `cloud-run:verify` completed with all checks passing.",
    "- [ ] Cloud Run service URL was checked with `/healthz`.",
    "- [ ] Remote MCP smoke passed against the deployed service URL.",
    "- [ ] Secret Manager references were verified without exposing secret values.",
    "- [ ] Service account secret-access bindings were confirmed for the deployed runtime service account.",
    "- [ ] Evidence was reviewed to confirm no raw Secret Manager values, bearer tokens, or draft contents are included.",
    "",
    "## Gate 12 Deployment Review Details",
    "",
    "- GCP project/region/service: <replace with non-sensitive project, region, and service reference>",
    "- Service URL checked: <replace with deployed Cloud Run HTTPS service URL and check reference>",
    "- Deploy command source: <replace with cloud-run:plan artifact or gcloud deploy command summary>",
    "- Health check result: <replace with /healthz status and timestamp>",
    "- Remote smoke result: <replace with auth-mode matching remote smoke command and result>",
    "- Auth mode deployed: <replace with noauth, static_bearer, or oauth and launch rationale>",
    "- Budget guard review: <replace with budget alert command/result or follow-up>",
    "- Path-secret review: <replace with not used or shell-only private path verification without the segment value>",
    "",
    "## Gate 13 Secret Manager Review Details",
    "",
    "- Secret references checked: <replace with Secret Manager reference check summary for SUBSTACK_SESSION_TOKEN and PREVIEW_TOKEN_SECRET>",
    "- Required secret names: <replace with session and preview Secret Manager resource names only, no values>",
    "- Runtime service account: <replace with deployed runtime service account email or service identity reference>",
    "- Secret access bindings: <replace with Secret Manager Secret Accessor IAM binding verification for the runtime service account>",
    "- Version policy: <replace with latest/pinned version decision and rotation notes>",
    "- Literal env review: <replace with confirmation secrets are references, not literal env values>",
    "- Secret value handling: <replace with confirmation no raw secret values were opened, pasted, exposed, or recorded>",
    "- Rotation follow-up: <replace with no-action reason or rotation/redeploy follow-up>",
    "",
    "## Suggested Record Commands",
    "",
    "```bash",
    formatV1RecordCommand({
      gateId: 12,
      evidence:
        "Cloud Run deployment config verified and deployed endpoint smoke passed",
      command: `${cloudRunVerifyEvidenceCommand(report, artifact)}; ${remoteSmokeEvidenceAction(report)}`,
      artifact,
    }),
    formatV1RecordCommand({
      gateId: 13,
      evidence:
        "Cloud Run service uses Secret Manager references for required runtime secrets",
      command: cloudRunVerifyEvidenceCommand(report, artifact),
      artifact,
    }),
    "```",
    "",
  ].join("\n")}\n`;
}

function cloudRunVerifyEvidenceCommand(
  report: CloudRunVerifyReport,
  artifact: string,
): string {
  return [
    "npm run cloud-run:verify --",
    "--service-json",
    ".data/cloud-run-service.json",
    ...(report.auth_mode === "static_bearer"
      ? []
      : ["--auth-mode", shellArg(report.auth_mode)]),
    ...expectedCheckValueArgs(report, "service_account", {
      expectedPrefix: "",
      flag: "--service-account-email",
      skipExpected: "configured service account",
    }),
    ...expectedCheckValueArgs(report, "env_substack_publication_url", {
      expectedPrefix: "SUBSTACK_PUBLICATION_URL=",
      flag: "--publication-url",
    }),
    ...expectedCheckValueArgs(report, "env_substack_user_id", {
      expectedPrefix: "SUBSTACK_USER_ID=",
      flag: "--user-id",
    }),
    ...expectedCheckValueArgs(report, "env_max_body_bytes", {
      expectedPrefix: "MAX_BODY_BYTES=",
      flag: "--max-body-bytes",
    }),
    ...expectedCheckValueArgs(report, "env_max_image_bytes", {
      expectedPrefix: "MAX_IMAGE_BYTES=",
      flag: "--max-image-bytes",
    }),
    ...expectedCheckValueArgs(report, "env_substack_request_timeout_ms", {
      expectedPrefix: "SUBSTACK_REQUEST_TIMEOUT_MS=",
      flag: "--substack-request-timeout-ms",
    }),
    ...expectedCheckValueArgs(report, "env_confirmation_token_ttl_seconds", {
      expectedPrefix: "CONFIRMATION_TOKEN_TTL_SECONDS=",
      flag: "--confirmation-token-ttl-seconds",
    }),
    ...expectedCheckValueArgs(report, "env_mcp_public_base_url", {
      expectedPrefix: "MCP_PUBLIC_BASE_URL=",
      flag: "--public-base-url",
    }),
    ...expectedCheckValueArgs(report, "env_oauth_authorization_server_url", {
      expectedPrefix: "OAUTH_AUTHORIZATION_SERVER_URL=",
      flag: "--oauth-authorization-server-url",
    }),
    ...expectedCheckValueArgs(report, "env_oauth_jwks_url", {
      expectedPrefix: "OAUTH_JWKS_URL=",
      flag: "--oauth-jwks-url",
    }),
    ...expectedCheckValueArgs(report, "env_oauth_resource_documentation_url", {
      expectedPrefix: "OAUTH_RESOURCE_DOCUMENTATION_URL=",
      flag: "--oauth-resource-documentation-url",
    }),
    ...expectedCheckValueArgs(report, "env_oauth_jwt_algorithms", {
      expectedPrefix: "OAUTH_JWT_ALGORITHMS=",
      flag: "--oauth-jwt-algorithms",
    }),
    "--evidence-artifact",
    shellArg(artifact),
  ].join(" ");
}

function expectedCheckValueArgs(
  report: CloudRunVerifyReport,
  checkId: string,
  options: {
    readonly expectedPrefix: string;
    readonly expectedSuffix?: string | undefined;
    readonly flag: string;
    readonly skipExpected?: string | undefined;
  },
): string[] {
  const expected = report.checks.find(
    (entry) => entry.id === checkId,
  )?.expected;
  if (!expected || expected === options.skipExpected) {
    return [];
  }

  if (
    !expected.startsWith(options.expectedPrefix) ||
    (options.expectedSuffix !== undefined &&
      !expected.endsWith(options.expectedSuffix))
  ) {
    return [];
  }

  const value = expected.slice(
    options.expectedPrefix.length,
    options.expectedSuffix === undefined
      ? expected.length
      : -options.expectedSuffix.length,
  );

  return value ? [options.flag, shellArg(value)] : [];
}

function remoteSmokeEvidenceAction(report: CloudRunVerifyReport): string {
  const mcpUrl = report.service_url
    ? `${report.service_url.replace(/\/+$/u, "")}/mcp`
    : "the deployed service MCP URL";

  switch (report.auth_mode) {
    case "noauth":
      return report.service_url
        ? `npm run smoke:remote-noauth -- --url ${shellArg(mcpUrl)}`
        : "run the noauth remote smoke against the deployed service MCP URL";
    case "oauth":
      return `run the OAuth remote smoke against ${mcpUrl} with a real access token`;
    case "static_bearer":
      return report.service_url
        ? `npm run smoke:remote -- --url ${shellArg(mcpUrl)}`
        : "run the static-bearer remote smoke against the deployed service MCP URL";
  }
}

function safeEvidenceDetail(value: string): string {
  return value.replace(
    /\b(SUBSTACK_SESSION_TOKEN|PREVIEW_TOKEN_SECRET|MCP_BEARER_TOKEN|MCP_PATH_SECRET)=/g,
    "$1 reference ",
  );
}

function resolveProjectArtifact(
  cwd: string,
  value: string,
): { readonly artifact: string; readonly path: string } {
  const root = resolve(cwd);
  const path = resolve(root, value);
  const artifact = relative(root, path);
  if (artifact === "" || artifact.startsWith("..") || isAbsolute(artifact)) {
    throw new Error(
      "V1 Cloud Run verify evidence artifact must stay inside the project directory.",
    );
  }

  return { artifact, path };
}
