import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import {
  fixtureCompatibilityTestCommand,
  fixtureStatusCommand,
} from "./fixtureStatusCore.js";
import { evidenceTextSafetyProblem } from "./v1EvidenceSafety.js";
import { formatV1RecordCommand, shellArg } from "./v1RecordCommandFormat.js";

type LiveGateArtifacts = Record<7 | 8 | 9, string>;

const DEFAULT_GATE_ARTIFACTS: LiveGateArtifacts = {
  7: ".data/v1/gate-07-rich-draft-live-fixtures.md",
  8: ".data/v1/gate-08-update-draft-live.md",
  9: ".data/v1/gate-09-read-drafts-live.md",
};

export interface LiveSubstackEvidence {
  readonly verified_at: string;
  readonly draft_id: number;
  readonly draft_url?: string | undefined;
  readonly created_title: string;
  readonly updated_title: string;
  readonly image_upload_verified: boolean;
  readonly create_verified: boolean;
  readonly list_verified: boolean;
  readonly get_verified: boolean;
  readonly update_verified: boolean;
  readonly post_update_get_verified: boolean;
}

export interface WriteLiveSubstackEvidenceOptions {
  readonly cwd: string;
  readonly artifact: string;
  readonly allArtifacts?: readonly string[] | undefined;
  readonly fixtureDir?: string | undefined;
  readonly evidence: LiveSubstackEvidence;
}

export interface WriteLiveSubstackEvidenceArtifactsOptions {
  readonly cwd: string;
  readonly artifacts: readonly string[];
  readonly fixtureDir?: string | undefined;
  readonly evidence: LiveSubstackEvidence;
}

export interface WriteLiveSubstackEvidenceResult {
  readonly artifact: string;
  readonly path: string;
}

export function parseLiveSubstackEvidenceArtifacts(
  env: Partial<Record<string, string | undefined>> = process.env,
): readonly string[] {
  const artifacts = [
    ...splitArtifactList(env.V1_LIVE_SUBSTACK_EVIDENCE_ARTIFACT),
    ...splitArtifactList(env.V1_LIVE_SUBSTACK_EVIDENCE_ARTIFACTS),
  ];
  return [...new Set(artifacts)];
}

export function writeLiveSubstackEvidenceArtifacts(
  options: WriteLiveSubstackEvidenceArtifactsOptions,
): readonly WriteLiveSubstackEvidenceResult[] {
  return options.artifacts.map((artifact) =>
    writeLiveSubstackEvidenceArtifact({
      cwd: options.cwd,
      artifact,
      allArtifacts: options.artifacts,
      fixtureDir: options.fixtureDir,
      evidence: options.evidence,
    }),
  );
}

export function writeLiveSubstackEvidenceArtifact(
  options: WriteLiveSubstackEvidenceOptions,
): WriteLiveSubstackEvidenceResult {
  const { artifact, path } = resolveLiveSubstackEvidenceArtifact(
    options.cwd,
    options.artifact,
  );
  const fixtureDirArg = resolveProjectFixtureDirArg(
    options.cwd,
    options.fixtureDir,
  );
  const markdown = renderLiveSubstackEvidenceArtifact(
    options.evidence,
    artifact,
    options.allArtifacts,
    fixtureDirArg,
  );
  const safetyProblem = evidenceTextSafetyProblem(
    `artifact ${artifact}`,
    markdown,
  );
  if (safetyProblem) {
    throw new Error(safetyProblem);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, markdown);
  return {
    artifact,
    path,
  };
}

export function renderLiveSubstackEvidenceArtifact(
  evidence: LiveSubstackEvidence,
  artifact?: string | undefined,
  allArtifacts?: readonly string[] | undefined,
  fixtureDirArg?: string | undefined,
): string {
  const gateArtifacts = liveGateArtifacts(artifact, allArtifacts);
  const liveCommand = liveSubstackCommand(artifact, allArtifacts);
  const richDraftCommand = richDraftEvidenceCommand(liveCommand, fixtureDirArg);
  const fixtureDir = fixtureDirArg ?? "fixtures/substack";
  const fixtureReadinessCommand = fixtureStatusCommand(fixtureDirArg, true);
  const fixtureCompatibilityCommand =
    fixtureCompatibilityTestCommand(fixtureDirArg);
  return `${[
    "# V1 Live Substack Draft Flow Evidence",
    "",
    "This artifact is generated by the guarded live Substack test. It records metadata only; do not add Substack session cookies, bearer tokens, preview secrets, raw API responses, or full draft contents.",
    "",
    "## Result",
    "",
    `- Verified at: ${evidence.verified_at}`,
    `- Draft ID: ${evidence.draft_id}`,
    `- Draft URL: ${evidence.draft_url ?? "not returned"}`,
    `- Created title: ${evidence.created_title}`,
    `- Updated title: ${evidence.updated_title}`,
    "",
    "## Automated Checks",
    "",
    checklistLine(
      evidence.image_upload_verified,
      "`upload_image` returned a hosted image URL.",
    ),
    checklistLine(evidence.create_verified, "`create_draft` created a draft."),
    checklistLine(
      evidence.list_verified,
      "`list_drafts` found the created draft.",
    ),
    checklistLine(
      evidence.get_verified,
      "`get_draft` fetched the created draft metadata.",
    ),
    checklistLine(
      evidence.update_verified,
      "`update_draft` updated the same draft.",
    ),
    checklistLine(
      evidence.post_update_get_verified,
      "`get_draft` fetched the updated draft metadata.",
    ),
    "",
    "## Gate 7 Manual Review Details",
    "",
    `- Fixture directory: ${fixtureDir}`,
    `- Fixture readiness command: \`${fixtureReadinessCommand}\``,
    `- Fixture compatibility command: \`${fixtureCompatibilityCommand}\``,
    "- Fixture provenance review:",
    `- Draft URL or ID: ${evidence.draft_url ?? evidence.draft_id}`,
    "- Title/subtitle review:",
    "- Text formatting review:",
    "- Image rendering review:",
    "- Native code block rendering review:",
    "- Native LaTeX rendering review:",
    "- Substack preview review:",
    "- Unpublished status review:",
    "- Cleanup decision:",
    "",
    "## Manual Review Checklist",
    "",
    "- [ ] Draft appears in the Substack dashboard.",
    "- [ ] Draft remains unpublished in Substack.",
    "- [ ] Title and subtitle are correct after the update.",
    "- [ ] Text formatting renders correctly: headings, rich text, links, lists, blockquote, and horizontal rule.",
    "- [ ] Rich draft review confirmed image rendering.",
    "- [ ] Rich draft review confirmed native code block rendering.",
    "- [ ] Rich draft review confirmed native LaTeX rendering.",
    "- [ ] Substack preview opens and renders the draft correctly.",
    "- [ ] Cleanup decision recorded: keep draft, delete draft, or leave for further manual review without publishing.",
    "",
    "## Gate 8 Update Review Details",
    "",
    `- Draft URL or ID: ${evidence.draft_url ?? evidence.draft_id}`,
    `- Created title before update: ${evidence.created_title}`,
    `- Updated title after update: ${evidence.updated_title}`,
    "- Update command: `RUN_LIVE_SUBSTACK_TESTS=1 npm run test:live`",
    "- Field update review:",
    "- Unpublished status after update:",
    "- Post-update `get_draft` review:",
    "- Draft body handling review:",
    "- Cleanup decision:",
    "",
    "## Gate 9 Read Review Details",
    "",
    `- Draft URL or ID read: ${evidence.draft_url ?? evidence.draft_id}`,
    "- `list_drafts` result:",
    "- `get_draft` result:",
    "- Metadata fields reviewed:",
    "- Body inclusion review:",
    "- Post-update readback review:",
    "- Raw body/content handling:",
    "- Follow-up action:",
    "",
    "## Suggested Record Commands",
    "",
    "```bash",
    formatV1RecordCommand({
      gateId: 7,
      evidence:
        "Live rich draft flow passed, fixtures were adapter-compatible, and manual formatting review completed",
      command: richDraftCommand,
      artifact: gateArtifacts[7],
    }),
    formatV1RecordCommand({
      gateId: 8,
      evidence: "Live update_draft flow updated an unpublished draft",
      command: liveCommand,
      artifact: gateArtifacts[8],
    }),
    formatV1RecordCommand({
      gateId: 9,
      evidence: "Live list_drafts and get_draft flow read the expected draft",
      command: liveCommand,
      artifact: gateArtifacts[9],
    }),
    "```",
    "",
  ].join("\n")}\n`;
}

function richDraftEvidenceCommand(
  liveCommand: string,
  fixtureDirArg: string | undefined,
): string {
  return [
    fixtureStatusCommand(fixtureDirArg, true),
    fixtureCompatibilityTestCommand(fixtureDirArg),
    liveCommand,
  ].join("; ");
}

function liveGateArtifacts(
  artifact: string | undefined,
  allArtifacts: readonly string[] | undefined,
): LiveGateArtifacts {
  if (allArtifacts && allArtifacts.length > 1) {
    return liveGateArtifactsFromList(allArtifacts);
  }

  if (!artifact) {
    return DEFAULT_GATE_ARTIFACTS;
  }

  return {
    7: artifact,
    8: artifact,
    9: artifact,
  };
}

function liveGateArtifactsFromList(
  artifacts: readonly string[],
): LiveGateArtifacts {
  const mapped: Partial<LiveGateArtifacts> = {};
  const unassigned: string[] = [];
  for (const artifact of artifacts) {
    const gateId = liveGateIdFromArtifact(artifact);
    if (gateId) {
      mapped[gateId] = artifact;
    } else {
      unassigned.push(artifact);
    }
  }

  const missingGateIds = ([7, 8, 9] as const).filter(
    (gateId) => mapped[gateId] === undefined,
  );
  for (const [index, gateId] of missingGateIds.entries()) {
    const artifact = unassigned[index];
    if (artifact) {
      mapped[gateId] = artifact;
    }
  }

  return {
    7: mapped[7] ?? DEFAULT_GATE_ARTIFACTS[7],
    8: mapped[8] ?? DEFAULT_GATE_ARTIFACTS[8],
    9: mapped[9] ?? DEFAULT_GATE_ARTIFACTS[9],
  };
}

function liveGateIdFromArtifact(artifact: string): 7 | 8 | 9 | undefined {
  const match = artifact.match(/(?:^|[/-])gate-0?(7|8|9)(?:[-.]|$)/u);
  if (!match) {
    return undefined;
  }

  return Number(match[1]) as 7 | 8 | 9;
}

function liveSubstackCommand(
  artifact: string | undefined,
  allArtifacts: readonly string[] | undefined,
): string {
  if (allArtifacts && allArtifacts.length > 1) {
    return `V1_LIVE_SUBSTACK_EVIDENCE_ARTIFACTS=${allArtifacts
      .map(shellArg)
      .join(",")} RUN_LIVE_SUBSTACK_TESTS=1 npm run test:live`;
  }

  if (artifact) {
    return `V1_LIVE_SUBSTACK_EVIDENCE_ARTIFACT=${shellArg(artifact)} RUN_LIVE_SUBSTACK_TESTS=1 npm run test:live`;
  }

  return `V1_LIVE_SUBSTACK_EVIDENCE_ARTIFACTS=${Object.values(
    DEFAULT_GATE_ARTIFACTS,
  ).join(",")} RUN_LIVE_SUBSTACK_TESTS=1 npm run test:live`;
}

function splitArtifactList(value: string | undefined): readonly string[] {
  return value
    ? value
        .split(/[,\n]/)
        .map((artifact) => artifact.trim())
        .filter((artifact) => artifact.length > 0)
    : [];
}

function checklistLine(checked: boolean, label: string): string {
  return `- [${checked ? "x" : " "}] ${label}`;
}

function resolveProjectArtifact(
  cwd: string,
  value: string,
): { readonly artifact: string; readonly path: string } {
  const root = resolve(cwd);
  const path = resolve(root, value);
  const artifact = relative(root, path);
  if (artifact === "" || artifact.startsWith("..") || isAbsolute(artifact)) {
    throw new Error(
      "V1 live evidence artifact must stay inside the project directory.",
    );
  }

  return { artifact, path };
}

export function resolveLiveSubstackEvidenceArtifact(
  cwd: string,
  value: string,
): { readonly artifact: string; readonly path: string } {
  return resolveProjectArtifact(cwd, value);
}

function resolveProjectFixtureDirArg(
  cwd: string,
  value: string | undefined,
): string | undefined {
  const trimmed = value?.trim();
  if (!trimmed) {
    return undefined;
  }
  if (/[\r\n]/u.test(trimmed)) {
    throw new Error(
      "V1 live fixture directory must be a single project-local path.",
    );
  }

  const root = resolve(cwd);
  const path = resolve(root, trimmed);
  if (path === resolve(root, "fixtures", "substack")) {
    return undefined;
  }

  const fixtureDir = relative(root, path);
  if (
    fixtureDir === "" ||
    fixtureDir.startsWith("..") ||
    isAbsolute(fixtureDir)
  ) {
    throw new Error(
      "V1 live fixture directory must stay inside the project directory.",
    );
  }

  return fixtureDir;
}
