import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";

import type { LocalStdioSmokeResult } from "./smokeLocalStdioCore.js";
import { evidenceTextSafetyProblem } from "./v1EvidenceSafety.js";
import { formatV1RecordCommand, shellArg } from "./v1RecordCommandFormat.js";

const DEFAULT_GATE_15_ARTIFACT = ".data/v1/gate-15-stdio-client.md";

export interface WriteLocalStdioEvidenceOptions {
  readonly cwd: string;
  readonly artifact: string;
  readonly result: LocalStdioSmokeResult;
  readonly verifiedAt?: string | undefined;
}

export interface WriteLocalStdioEvidenceResult {
  readonly artifact: string;
  readonly path: string;
}

export function writeLocalStdioEvidenceArtifact(
  options: WriteLocalStdioEvidenceOptions,
): WriteLocalStdioEvidenceResult {
  const { artifact, path } = resolveProjectArtifact(
    options.cwd,
    options.artifact,
  );
  const markdown = renderLocalStdioEvidenceArtifact(
    options.result,
    options.verifiedAt ?? new Date().toISOString(),
    artifact,
  );
  const safetyProblem = evidenceTextSafetyProblem(
    `artifact ${artifact}`,
    markdown,
  );
  if (safetyProblem) {
    throw new Error(safetyProblem);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, markdown);

  return {
    artifact,
    path,
  };
}

export function renderLocalStdioEvidenceArtifact(
  result: LocalStdioSmokeResult,
  verifiedAt: string,
  artifact = DEFAULT_GATE_15_ARTIFACT,
): string {
  return `${[
    "# V1 Stdio Client Evidence",
    "",
    "This artifact is generated by the local stdio smoke test. It records safe transport and tool metadata only; do not add Substack cookies, bearer tokens, preview secrets, raw API responses, or full draft contents.",
    "",
    "## Automated Stdio Smoke",
    "",
    `- Verified at: ${verifiedAt}`,
    `- Transport: ${result.transport}`,
    `- Command: ${result.command}`,
    `- Arguments: ${result.args.length > 0 ? result.args.join(" ") : "(none)"}`,
    `- Tool count: ${result.tool_count}`,
    `- Tools: ${result.tools.join(", ")}`,
    "",
    "## Validation Fixture",
    "",
    `- Fixture: ${result.validation.fixture}`,
    `- Blocks: ${result.validation.blocks}`,
    `- Words: ${result.validation.words}`,
    `- Images: ${result.validation.images}`,
    `- Code blocks: ${result.validation.code_blocks}`,
    `- LaTeX blocks: ${result.validation.latex_blocks}`,
    `- Links: ${result.validation.links}`,
    `- Validation warnings: ${result.validation.warning_count}`,
    `- Unsupported features: ${result.validation.unsupported_features.join(", ") || "none"}`,
    "",
    "## Preview Fixture",
    "",
    `- Fixture: ${result.preview.fixture}`,
    `- Action: ${result.preview.action}`,
    `- Title: ${result.preview.title}`,
    `- Blocks: ${result.preview.blocks}`,
    `- Words: ${result.preview.words}`,
    `- Images: ${result.preview.images}`,
    `- Code blocks: ${result.preview.code_blocks}`,
    `- LaTeX blocks: ${result.preview.latex_blocks}`,
    `- Preview warnings: ${result.preview.warning_count}`,
    `- Confirmation token parts: ${result.preview.confirmation_token_parts}`,
    `- Confirmation expiry: ${result.preview.confirmation_expires_at}`,
    `- Preview text characters: ${result.preview.preview_text_chars}`,
    `- Preview document type: ${result.preview.payload_debug_doc_type}`,
    `- Preview top-level nodes: ${result.preview.payload_debug_top_level_nodes}`,
    "",
    "## Required Evidence Checklist",
    "",
    "- [x] Built stdio entrypoint launched and exposed exactly the seven V1 draft-workflow tools.",
    "- [x] `validate_newsletter_content` completed against the rich Markdown fixture.",
    "- [x] `preview_draft` completed without calling Substack or write tools.",
    "- [ ] Built package configured in Claude Code or Cursor through stdio.",
    "- [ ] Claude Code or Cursor listed the same seven V1 draft-workflow tools.",
    "- [ ] Claude Code or Cursor called `validate_newsletter_content` successfully.",
    "- [ ] Credentials remained local and were not exposed to a remote host.",
    "",
    "## Manual Client Acceptance",
    "",
    "Complete these fields after testing a real local MCP client. Leave out raw tool responses, full draft contents, and secret values.",
    "",
    "- Client tested: <replace with Claude Code or Cursor version>",
    "- Config path or add command: <replace with Claude Code/Cursor stdio config path or add command>",
    "- Server entrypoint path: <replace with absolute path to dist/stdio.js>",
    "- Tool-list result: <replace with exact seven V1 draft-workflow tools listed through Claude Code or Cursor>",
    "- Validation call result: <replace with validate_newsletter_content success through Claude Code or Cursor>",
    "- Credential locality review: <replace with confirmation that Substack credentials came from local environment variables and were not recorded, committed, pasted into client config, or exposed remotely>",
    "",
    "## Suggested Record Command",
    "",
    "```bash",
    formatV1RecordCommand({
      gateId: 15,
      evidence:
        "Built stdio package passed smoke test and Claude Code/Cursor client acceptance checklist",
      command: `npm run smoke:stdio -- --evidence-artifact ${shellArg(artifact)}; Claude Code/Cursor stdio manual workflow`,
      artifact,
    }),
    "```",
    "",
  ].join("\n")}\n`;
}

function resolveProjectArtifact(
  cwd: string,
  value: string,
): { readonly artifact: string; readonly path: string } {
  const root = resolve(cwd);
  const path = resolve(root, value);
  const artifact = relative(root, path);
  if (artifact === "" || artifact.startsWith("..") || isAbsolute(artifact)) {
    throw new Error(
      "V1 stdio evidence artifact must stay inside the project directory.",
    );
  }

  return { artifact, path };
}
