import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import type { LocalHttpSmokeResult } from "./smokeLocalHttpCore.js";
import { redactRemoteUrl } from "./smokeRemoteHttpCore.js";
import { evidenceTextSafetyProblem } from "./v1EvidenceSafety.js";

export interface WriteLocalHttpEvidenceOptions {
  readonly cwd: string;
  readonly artifact: string;
  readonly result: LocalHttpSmokeResult;
  readonly verifiedAt?: string | undefined;
}

export interface WriteLocalHttpEvidenceResult {
  readonly artifact: string;
  readonly path: string;
}

export function writeLocalHttpEvidenceArtifact(
  options: WriteLocalHttpEvidenceOptions,
): WriteLocalHttpEvidenceResult {
  const { artifact, path } = resolveProjectArtifact(
    options.cwd,
    options.artifact,
  );
  const markdown = renderLocalHttpEvidenceArtifact(
    options.result,
    options.verifiedAt ?? new Date().toISOString(),
  );
  const safetyProblem = evidenceTextSafetyProblem(
    `artifact ${artifact}`,
    markdown,
  );
  if (safetyProblem) {
    throw new Error(safetyProblem);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, markdown);

  return {
    artifact,
    path,
  };
}

export function renderLocalHttpEvidenceArtifact(
  result: LocalHttpSmokeResult,
  verifiedAt: string,
): string {
  const endpoint = redactRemoteUrl(new URL(result.endpoint));

  return `${[
    "# V1 MCP Inspector Evidence",
    "",
    "This artifact is generated by the local HTTP smoke test. It records safe endpoint and tool metadata only; do not add Substack cookies, bearer tokens, preview secrets, raw API responses, screenshots with secrets, or full draft contents.",
    "",
    "## Automated Local HTTP Smoke",
    "",
    `- Verified at: ${verifiedAt}`,
    `- Transport: ${result.transport}`,
    `- MCP endpoint: ${endpoint}`,
    `- Health URL: ${result.health.url}`,
    `- Health status: ${result.health.status}`,
    `- Command: ${result.command}`,
    `- Arguments: ${result.args.length > 0 ? result.args.join(" ") : "(none)"}`,
    `- Tool count: ${result.tool_count}`,
    `- Tools: ${result.tools.join(", ")}`,
    "",
    "## MCP Inspector CLI",
    "",
    ...(result.inspector
      ? [
          `- Command: ${result.inspector.command}`,
          `- Arguments: ${formatInspectorArgs(result.inspector.args).join(" ")}`,
          `- Method: ${result.inspector.method}`,
          `- Tool count: ${result.inspector.tool_count}`,
          `- Tools: ${result.inspector.tools.join(", ")}`,
        ]
      : [
          "- Status: not run",
          "- To include an automated Inspector pass, rerun with `--inspector-cli`.",
        ]),
    "",
    "## Validation Fixture",
    "",
    `- Fixture: ${result.validation.fixture}`,
    `- Blocks: ${result.validation.blocks}`,
    `- Words: ${result.validation.words}`,
    `- Images: ${result.validation.images}`,
    `- Code blocks: ${result.validation.code_blocks}`,
    `- LaTeX blocks: ${result.validation.latex_blocks}`,
    `- Links: ${result.validation.links}`,
    `- Validation warnings: ${result.validation.warning_count}`,
    `- Unsupported features: ${result.validation.unsupported_features.join(", ") || "none"}`,
    "",
    "## Preview Fixture",
    "",
    `- Fixture: ${result.preview.fixture}`,
    `- Action: ${result.preview.action}`,
    `- Title: ${result.preview.title}`,
    `- Blocks: ${result.preview.blocks}`,
    `- Words: ${result.preview.words}`,
    `- Images: ${result.preview.images}`,
    `- Code blocks: ${result.preview.code_blocks}`,
    `- LaTeX blocks: ${result.preview.latex_blocks}`,
    `- Preview warnings: ${result.preview.warning_count}`,
    `- Confirmation token parts: ${result.preview.confirmation_token_parts}`,
    `- Confirmation expiry: ${result.preview.confirmation_expires_at}`,
    `- Preview text characters: ${result.preview.preview_text_chars}`,
    `- Preview document type: ${result.preview.payload_debug_doc_type}`,
    `- Preview top-level nodes: ${result.preview.payload_debug_top_level_nodes}`,
    "",
    "## Required Evidence Checklist",
    "",
    "- [x] Local HTTP endpoint responded on `/healthz`.",
    "- [x] Local HTTP smoke listed exactly the seven V1 draft-only tools.",
    "- [x] `validate_newsletter_content` completed against the rich Markdown fixture.",
    "- [x] `preview_draft` completed without calling Substack or write tools.",
    `${result.inspector ? "- [x]" : "- [ ]"} MCP Inspector CLI connected to the local HTTP \`/mcp\` endpoint.`,
    `${result.inspector ? "- [x]" : "- [ ]"} MCP Inspector CLI listed the same seven V1 draft-only tools.`,
    `${result.inspector ? "- [x]" : "- [ ]"} MCP Inspector CLI did not show publish, schedule, delete, email, or Notes tools.`,
    "- [ ] Evidence was reviewed to confirm no secrets or draft contents are included.",
    "",
    "## Suggested Inspector Command",
    "",
    "```bash",
    "npx --yes @modelcontextprotocol/inspector@latest --cli http://localhost:8787/mcp --method tools/list --transport http",
    "```",
    "",
    "## Release Note",
    "",
    "Gate 3 is tracked as repo-local evidence by `npm run v1:status`; no `v1:record` entry is needed for this artifact.",
    "Keep this artifact with release notes when making a V1 acceptance decision.",
    "",
  ].join("\n")}\n`;
}

function formatInspectorArgs(args: readonly string[]): string[] {
  return args.map((arg) => {
    try {
      const url = new URL(arg);
      return redactRemoteUrl(url);
    } catch {
      return arg;
    }
  });
}

function resolveProjectArtifact(
  cwd: string,
  value: string,
): { readonly artifact: string; readonly path: string } {
  const root = resolve(cwd);
  const path = resolve(root, value);
  const artifact = relative(root, path);
  if (artifact === "" || artifact.startsWith("..") || isAbsolute(artifact)) {
    throw new Error(
      "V1 local HTTP evidence artifact must stay inside the project directory.",
    );
  }

  return { artifact, path };
}
