import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";

import type { RemoteOAuthSmokeResult } from "./smokeRemoteOAuthHttpCore.js";
import {
  evidenceTextSafetyProblem,
  requiredRemoteOAuthLaunchChecklistLabels,
} from "./v1EvidenceSafety.js";

const DEFAULT_REMOTE_OAUTH_ARTIFACT = ".data/v1/remote-oauth.md";

export interface WriteRemoteOAuthEvidenceOptions {
  readonly cwd: string;
  readonly artifact: string;
  readonly result: RemoteOAuthSmokeResult;
  readonly verifiedAt?: string | undefined;
}

export interface WriteRemoteOAuthEvidenceResult {
  readonly artifact: string;
  readonly path: string;
}

export function writeRemoteOAuthEvidenceArtifact(
  options: WriteRemoteOAuthEvidenceOptions,
): WriteRemoteOAuthEvidenceResult {
  const { artifact, path } = resolveProjectArtifact(
    options.cwd,
    options.artifact,
  );
  const markdown = renderRemoteOAuthEvidenceArtifact(
    options.result,
    options.verifiedAt ?? new Date().toISOString(),
    artifact,
  );
  const safetyProblem = evidenceTextSafetyProblem(
    `artifact ${artifact}`,
    markdown,
  );
  if (safetyProblem) {
    throw new Error(safetyProblem);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, markdown);

  return {
    artifact,
    path,
  };
}

export function renderRemoteOAuthEvidenceArtifact(
  result: RemoteOAuthSmokeResult,
  verifiedAt: string,
  artifact = DEFAULT_REMOTE_OAUTH_ARTIFACT,
): string {
  return `${[
    "# V1 Remote OAuth Evidence",
    "",
    "This artifact is generated by the remote OAuth smoke test. It records safe endpoint, metadata, and tool results only; do not add OAuth access tokens, authorization codes, refresh tokens, Substack cookies, raw API responses, or full draft contents.",
    "",
    "## Automated Remote Smoke",
    "",
    `- Verified at: ${verifiedAt}`,
    `- Auth mode: ${result.auth_mode}`,
    `- MCP endpoint: ${result.endpoint}`,
    `- Health URL: ${result.health.url}`,
    `- Health status: ${result.health.status}`,
    `- Protected resource metadata URL: ${result.protected_resource_metadata_url}`,
    `- OAuth resource: ${result.metadata.resource}`,
    `- Authorization servers: ${result.metadata.authorization_servers.join(", ")}`,
    `- Scopes supported: ${result.metadata.scopes_supported.join(", ")}`,
    `- Metadata CORS allow-origin: ${result.metadata_cors.metadata_allow_origin}`,
    `- Metadata CORS preflight status: ${result.metadata_cors.preflight_status}`,
    `- Metadata CORS preflight allows authorization: ${result.metadata_cors.preflight_allows_authorization ? "yes" : "no"}`,
    `- Metadata CORS preflight exposes WWW-Authenticate: ${result.metadata_cors.preflight_exposes_www_authenticate ? "yes" : "no"}`,
    `- Authorization server discovery URL: ${result.authorization_server.discovery_url}`,
    `- Authorization server discovery type: ${result.authorization_server.discovery_type}`,
    `- Authorization server issuer: ${result.authorization_server.issuer}`,
    `- Authorization endpoint: ${result.authorization_server.authorization_endpoint}`,
    `- Token endpoint: ${result.authorization_server.token_endpoint}`,
    `- JWKS URI: ${result.authorization_server.jwks_uri}`,
    `- Authorization grant types: ${result.authorization_server.grant_types_supported.join(", ")}`,
    `- Authorization response types: ${result.authorization_server.response_types_supported.join(", ")}`,
    `- PKCE methods: ${result.authorization_server.code_challenge_methods_supported.join(", ")}`,
    `- Tool count: ${result.tool_count}`,
    `- Tools: ${result.tools.join(", ")}`,
    "",
    "## Validation Fixture",
    "",
    `- Fixture: ${result.validation.fixture}`,
    `- Blocks: ${result.validation.blocks}`,
    `- Words: ${result.validation.words}`,
    `- Images: ${result.validation.images}`,
    `- Code blocks: ${result.validation.code_blocks}`,
    `- LaTeX blocks: ${result.validation.latex_blocks}`,
    `- Links: ${result.validation.links}`,
    `- Validation warnings: ${result.validation.warning_count}`,
    `- Unsupported features: ${result.validation.unsupported_features.join(", ") || "none"}`,
    "",
    "## Preview Fixture",
    "",
    `- Fixture: ${result.preview.fixture}`,
    `- Action: ${result.preview.action}`,
    `- Title: ${result.preview.title}`,
    `- Blocks: ${result.preview.blocks}`,
    `- Words: ${result.preview.words}`,
    `- Images: ${result.preview.images}`,
    `- Code blocks: ${result.preview.code_blocks}`,
    `- LaTeX blocks: ${result.preview.latex_blocks}`,
    `- Preview warnings: ${result.preview.warning_count}`,
    `- Confirmation token parts: ${result.preview.confirmation_token_parts}`,
    `- Confirmation expiry: ${result.preview.confirmation_expires_at}`,
    `- Preview text characters: ${result.preview.preview_text_chars}`,
    `- Preview document type: ${result.preview.payload_debug_doc_type}`,
    `- Preview top-level nodes: ${result.preview.payload_debug_top_level_nodes}`,
    "",
    "## Required OAuth Launch Checklist",
    "",
    ...requiredRemoteOAuthLaunchChecklistLabels().map(
      (label, index) => `- [${index < 8 ? "x" : " "}] ${label}`,
    ),
    "",
    "## Manual OAuth Launch Review",
    "",
    "Complete these fields after testing the intended authorization server and ChatGPT connector. Leave out OAuth access tokens, authorization codes, refresh tokens, ID tokens, JWKS private keys, raw tool responses, full draft contents, screenshots with secrets, and private credentials.",
    "",
    `- Evidence artifact: ${artifact}`,
    "- Authorization server tested: <replace with issuer or authorization server reference plus discovery review>",
    "- OAuth client tested: <replace with ChatGPT connector/client identifier>",
    "- Browser login result: <replace with authorization-code + PKCE browser login completion summary>",
    "- Connector registration result: <replace with ChatGPT connector registration or linking summary>",
    "- Protected-resource metadata result: <replace with protected-resource metadata, CORS, and challenge review summary>",
    "- Token validation result: <replace with issuer, audience/resource, expiry, and scope checks summary>",
    "- Tool-list result: <replace with exact seven V1 draft-only tool names>",
    "- Validation call result: <replace with validate_newsletter_content success summary>",
    "- Preview call result: <replace with preview_draft success summary>",
    "- Error-path result: <replace with missing, expired, wrong-audience, or invalid token rejection summary>",
    "- Token redaction review: <replace with confirmation no token, code, credential, or secret value is included, recorded, pasted, exposed, or logged>",
    "- Launch decision: <replace with durable ChatGPT OAuth launch ready/deferred and reason or follow-up action>",
    "",
    "## Launch Boundary",
    "",
    "This artifact is not a numbered V1 gate record. It supports the plan's durable/public ChatGPT OAuth launch criterion; keep numbered V1 gate evidence in the gate-specific artifacts under `.data/v1/`.",
    "",
  ].join("\n")}\n`;
}

function resolveProjectArtifact(
  cwd: string,
  value: string,
): { readonly artifact: string; readonly path: string } {
  const root = resolve(cwd);
  const path = resolve(root, value);
  const artifact = relative(root, path);
  if (artifact === "" || artifact.startsWith("..") || isAbsolute(artifact)) {
    throw new Error(
      "V1 remote OAuth evidence artifact must stay inside the project directory.",
    );
  }

  return { artifact, path };
}
