import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";

import type { RemoteSmokeResult } from "./smokeRemoteHttpCore.js";
import { evidenceTextSafetyProblem } from "./v1EvidenceSafety.js";
import { formatV1RecordCommand, shellArg } from "./v1RecordCommandFormat.js";

const DEFAULT_GATE_14_ARTIFACT = ".data/v1/gate-14-static-bearer-remote.md";

export interface WriteRemoteStaticBearerEvidenceOptions {
  readonly cwd: string;
  readonly artifact: string;
  readonly result: RemoteSmokeResult;
  readonly verifiedAt?: string | undefined;
}

export interface WriteRemoteStaticBearerEvidenceResult {
  readonly artifact: string;
  readonly path: string;
}

export function writeRemoteStaticBearerEvidenceArtifact(
  options: WriteRemoteStaticBearerEvidenceOptions,
): WriteRemoteStaticBearerEvidenceResult {
  const { artifact, path } = resolveProjectArtifact(
    options.cwd,
    options.artifact,
  );
  const markdown = renderRemoteStaticBearerEvidenceArtifact(
    options.result,
    options.verifiedAt ?? new Date().toISOString(),
    artifact,
  );
  const safetyProblem = evidenceTextSafetyProblem(
    `artifact ${artifact}`,
    markdown,
  );
  if (safetyProblem) {
    throw new Error(safetyProblem);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, markdown);

  return {
    artifact,
    path,
  };
}

export function renderRemoteStaticBearerEvidenceArtifact(
  result: RemoteSmokeResult,
  verifiedAt: string,
  artifact = DEFAULT_GATE_14_ARTIFACT,
): string {
  return `${[
    "# V1 Static Bearer Remote Evidence",
    "",
    "This artifact is generated by the remote static-bearer smoke test. It records safe endpoint and tool metadata only; do not add bearer tokens, Substack cookies, preview secrets, raw API responses, or full draft contents.",
    "",
    "## Automated Remote Smoke",
    "",
    `- Verified at: ${verifiedAt}`,
    `- Auth mode: ${result.auth_mode}`,
    `- MCP endpoint: ${result.endpoint}`,
    `- Health URL: ${result.health.url}`,
    `- Health status: ${result.health.status}`,
    `- Missing bearer status: ${result.missing_bearer_status}`,
    `- Wrong bearer status: ${result.wrong_bearer_status}`,
    `- Tool count: ${result.tool_count}`,
    `- Tools: ${result.tools.join(", ")}`,
    "",
    "## Validation Fixture",
    "",
    `- Fixture: ${result.validation.fixture}`,
    `- Blocks: ${result.validation.blocks}`,
    `- Words: ${result.validation.words}`,
    `- Images: ${result.validation.images}`,
    `- Code blocks: ${result.validation.code_blocks}`,
    `- LaTeX blocks: ${result.validation.latex_blocks}`,
    `- Links: ${result.validation.links}`,
    `- Validation warnings: ${result.validation.warning_count}`,
    `- Unsupported features: ${result.validation.unsupported_features.join(", ") || "none"}`,
    "",
    "## Preview Fixture",
    "",
    `- Fixture: ${result.preview.fixture}`,
    `- Action: ${result.preview.action}`,
    `- Title: ${result.preview.title}`,
    `- Blocks: ${result.preview.blocks}`,
    `- Words: ${result.preview.words}`,
    `- Images: ${result.preview.images}`,
    `- Code blocks: ${result.preview.code_blocks}`,
    `- LaTeX blocks: ${result.preview.latex_blocks}`,
    `- Preview warnings: ${result.preview.warning_count}`,
    `- Confirmation token parts: ${result.preview.confirmation_token_parts}`,
    `- Confirmation expiry: ${result.preview.confirmation_expires_at}`,
    `- Preview text characters: ${result.preview.preview_text_chars}`,
    `- Preview document type: ${result.preview.payload_debug_doc_type}`,
    `- Preview top-level nodes: ${result.preview.payload_debug_top_level_nodes}`,
    "",
    "## Required Evidence Checklist",
    "",
    "- [x] Remote endpoint responded on `/healthz`.",
    "- [x] Missing bearer token was rejected with HTTP 401.",
    "- [x] Wrong bearer token was rejected with HTTP 401.",
    "- [x] Remote static-bearer MCP endpoint accepted the configured bearer token.",
    "- [x] Endpoint listed exactly the seven V1 draft-workflow tools.",
    "- [x] `validate_newsletter_content` completed against the rich Markdown fixture.",
    "- [x] `preview_draft` completed without calling Substack or write tools.",
    "- [ ] At least one real HTTP client that supports headers was configured with the bearer token.",
    "- [ ] Evidence was reviewed to confirm no bearer token or token value is included, recorded, printed, pasted, exposed, or logged.",
    "",
    "## Manual Header-Capable Client Acceptance",
    "",
    "Complete these fields after testing a real HTTP client that can send custom headers. Leave out bearer token values, raw tool responses, full draft contents, and secret values.",
    "",
    "- Client tested: <replace with real header-capable HTTP client name and version>",
    "- Endpoint tested: <replace with public HTTPS /mcp endpoint tested through the header-capable client>",
    "- Header configuration method: <replace with how Authorization header was configured without the token value>",
    "- Tool-list result: <replace with exact seven V1 draft-workflow tools listed through the client>",
    "- Validation call result: <replace with validate_newsletter_content success through the client>",
    "- Rejection proof: <replace with missing and wrong bearer 401 rejection command or artifact reference>",
    "- Token redaction review: <replace with confirmation that no bearer token or token value is included, recorded, printed, pasted, exposed, or logged>",
    "",
    "## Suggested Record Command",
    "",
    "```bash",
    formatV1RecordCommand({
      gateId: 14,
      evidence:
        "Remote static-bearer smoke passed and header-capable client checklist completed",
      command: `npm run smoke:remote -- --url ${shellArg(result.endpoint)} --evidence-artifact ${shellArg(artifact)}; header-capable client manual workflow`,
      artifact,
    }),
    "```",
    "",
  ].join("\n")}\n`;
}

function resolveProjectArtifact(
  cwd: string,
  value: string,
): { readonly artifact: string; readonly path: string } {
  const root = resolve(cwd);
  const path = resolve(root, value);
  const artifact = relative(root, path);
  if (artifact === "" || artifact.startsWith("..") || isAbsolute(artifact)) {
    throw new Error(
      "V1 remote static-bearer evidence artifact must stay inside the project directory.",
    );
  }

  return { artifact, path };
}
