import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";

import type { RemoteNoAuthSmokeResult } from "./smokeRemoteNoAuthHttpCore.js";
import { evidenceTextSafetyProblem } from "./v1EvidenceSafety.js";
import { formatV1RecordCommand, shellArg } from "./v1RecordCommandFormat.js";

const DEFAULT_GATE_11_ARTIFACT = ".data/v1/gate-11-chatgpt-ngrok.md";

export interface WriteRemoteNoAuthEvidenceOptions {
  readonly cwd: string;
  readonly artifact: string;
  readonly result: RemoteNoAuthSmokeResult;
  readonly verifiedAt?: string | undefined;
}

export interface WriteRemoteNoAuthEvidenceResult {
  readonly artifact: string;
  readonly path: string;
}

export function writeRemoteNoAuthEvidenceArtifact(
  options: WriteRemoteNoAuthEvidenceOptions,
): WriteRemoteNoAuthEvidenceResult {
  const { artifact, path } = resolveProjectArtifact(
    options.cwd,
    options.artifact,
  );
  const markdown = renderRemoteNoAuthEvidenceArtifact(
    options.result,
    options.verifiedAt ?? new Date().toISOString(),
    artifact,
  );
  const safetyProblem = evidenceTextSafetyProblem(
    `artifact ${artifact}`,
    markdown,
  );
  if (safetyProblem) {
    throw new Error(safetyProblem);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, markdown);

  return {
    artifact,
    path,
  };
}

export function renderRemoteNoAuthEvidenceArtifact(
  result: RemoteNoAuthSmokeResult,
  verifiedAt: string,
  artifact = DEFAULT_GATE_11_ARTIFACT,
): string {
  return `${[
    "# V1 ChatGPT Ngrok Evidence",
    "",
    "This artifact is generated by the remote noauth smoke test. It records safe endpoint and tool metadata only; do not add Substack cookies, bearer tokens, preview secrets, raw API responses, or full draft contents.",
    "",
    "## Automated Remote Smoke",
    "",
    `- Verified at: ${verifiedAt}`,
    `- Auth mode: ${result.auth_mode}`,
    `- MCP endpoint: ${result.endpoint}`,
    `- Health URL: ${result.health.url}`,
    `- Health status: ${result.health.status}`,
    `- Tool count: ${result.tool_count}`,
    `- Tools: ${result.tools.join(", ")}`,
    "",
    "## Validation Fixture",
    "",
    `- Fixture: ${result.validation.fixture}`,
    `- Blocks: ${result.validation.blocks}`,
    `- Words: ${result.validation.words}`,
    `- Images: ${result.validation.images}`,
    `- Code blocks: ${result.validation.code_blocks}`,
    `- LaTeX blocks: ${result.validation.latex_blocks}`,
    `- Links: ${result.validation.links}`,
    `- Validation warnings: ${result.validation.warning_count}`,
    `- Unsupported features: ${result.validation.unsupported_features.join(", ") || "none"}`,
    "",
    "## Preview Fixture",
    "",
    `- Fixture: ${result.preview.fixture}`,
    `- Action: ${result.preview.action}`,
    `- Title: ${result.preview.title}`,
    `- Blocks: ${result.preview.blocks}`,
    `- Words: ${result.preview.words}`,
    `- Images: ${result.preview.images}`,
    `- Code blocks: ${result.preview.code_blocks}`,
    `- LaTeX blocks: ${result.preview.latex_blocks}`,
    `- Preview warnings: ${result.preview.warning_count}`,
    `- Confirmation token parts: ${result.preview.confirmation_token_parts}`,
    `- Confirmation expiry: ${result.preview.confirmation_expires_at}`,
    `- Preview text characters: ${result.preview.preview_text_chars}`,
    `- Preview document type: ${result.preview.payload_debug_doc_type}`,
    `- Preview top-level nodes: ${result.preview.payload_debug_top_level_nodes}`,
    "",
    "## Required Evidence Checklist",
    "",
    "- [x] Remote endpoint responded on `/healthz`.",
    "- [x] Remote noauth MCP endpoint listed exactly the seven V1 draft-only tools.",
    "- [x] `validate_newsletter_content` completed against the rich Markdown fixture.",
    "- [x] `preview_draft` completed without calling Substack or write tools.",
    "- [ ] ChatGPT connector was registered with the same HTTPS `/mcp` endpoint.",
    "- [ ] ChatGPT listed the same seven V1 draft-only tools.",
    "- [ ] ChatGPT completed the intended manual draft flow.",
    "- [ ] Tunnel exposure was short-lived, unexpected traffic was checked, and session-token rotation decision was recorded.",
    "",
    "## Manual ChatGPT Connector Acceptance",
    "",
    "Complete these fields after testing the connector in ChatGPT. Leave out Substack cookies, raw tool responses, full draft contents, screenshots with secrets, and private credentials.",
    "",
    "- Connector URL: <replace with public HTTPS /mcp URL or screenshot reference>",
    "- ChatGPT surface tested: <replace with workspace/account or connector screen reference>",
    "- Tool-list result: <replace with exactly seven V1 draft-only tools listed through the ChatGPT connector>",
    "- Manual flow result: <replace with ChatGPT validate/preview/create draft summary>",
    "- Draft or review reference: <replace with non-sensitive Substack draft URL, numeric draft ID, screenshot reference, or manual review reference>",
    "- Tunnel exposure window: <replace with bounded start/end time or numeric duration>",
    "- Unexpected traffic review: <replace with checked ngrok/local logs and no unexpected traffic or handled findings>",
    "- Rotation decision: <replace with rotated/stopped/not rotated plus reason>",
    "",
    "## Suggested Record Command",
    "",
    "```bash",
    formatV1RecordCommand({
      gateId: 11,
      evidence:
        "Remote noauth smoke passed and ChatGPT connector manual checklist completed",
      command: `npm run smoke:remote-noauth -- --url ${shellArg(result.endpoint)} --evidence-artifact ${shellArg(artifact)}; ChatGPT connector manual workflow`,
      artifact,
    }),
    "```",
    "",
  ].join("\n")}\n`;
}

function resolveProjectArtifact(
  cwd: string,
  value: string,
): { readonly artifact: string; readonly path: string } {
  const root = resolve(cwd);
  const path = resolve(root, value);
  const artifact = relative(root, path);
  if (artifact === "" || artifact.startsWith("..") || isAbsolute(artifact)) {
    throw new Error(
      "V1 remote noauth evidence artifact must stay inside the project directory.",
    );
  }

  return { artifact, path };
}
